// report.go renders captured scenarios: console by default, one self-contained
// static HTML file with -html <path>.
package main

import (
	"fmt"
	"html"
	"io"
	"strings"
)

// Question is verbatim from the #1308 brief; it heads every report.
const Question = "Do the decided envelope (#1304), seal tags (#1305), family-kid keys (#1306) and replay slots (#1307) compose into a producer/consumer DX that feels right — and do a tampered clear field, a wrong key, a strip-and-re-sign, a rotation overlap, a cross-type reroute, a tenant mismatch and an unsealed body all fail exactly the way those decisions say?"

// ---------------------------------------------------------------------------
// Console
// ---------------------------------------------------------------------------

func RenderConsole(w io.Writer, scenarios []*Scenario) {
	fmt.Fprintf(w, "QUESTION: %s\n\n", Question)
	for _, s := range scenarios {
		fmt.Fprintf(w, "%s\n%s\n%s\n\n", strings.Repeat("=", 100), s.Title, s.Description)
		for _, st := range s.Steps {
			marker := "  "
			if st.Failed {
				marker = "✗ "
			}
			fmt.Fprintf(w, "%s--- %s\n", marker, st.Title)
			if st.Text != "" {
				fmt.Fprintf(w, "    %s\n", st.Text)
			}
			for _, kv := range st.State {
				fmt.Fprintf(w, "    [%s]\n%s\n", kv.Label, indent(kv.Value, "      "))
			}
			fmt.Fprintln(w)
		}
	}
}

func indent(s, prefix string) string {
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		lines[i] = prefix + l
	}
	return strings.Join(lines, "\n")
}

// ---------------------------------------------------------------------------
// HTML (CSS-only tabs via radio inputs; one accent colour; inline CSS)
// ---------------------------------------------------------------------------

const htmlHead = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Seal/Open Walkthrough — #1308</title>
<style>
:root{--accent:#2f6f8f;--ink:#1f2328;--muted:#6a737d;--line:#e3e6ea;--bg:#fafbfc;--fail:#b42318;--mono:ui-monospace,SFMono-Regular,Menlo,monospace}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 system-ui,-apple-system,Segoe UI,sans-serif}
header{padding:28px 32px 18px;border-bottom:1px solid var(--line);background:#fff}
header h1{margin:0 0 8px;font-size:20px;font-weight:600}header p{margin:0;max-width:110ch;color:var(--muted)}
header .q{color:var(--ink);font-size:16px;margin-bottom:10px}
nav{display:flex;flex-wrap:wrap;gap:4px;padding:12px 32px;background:#fff;border-bottom:1px solid var(--line);position:sticky;top:0}
nav label{padding:6px 12px;border:1px solid var(--line);border-radius:6px;cursor:pointer;font-size:13px;color:var(--muted);background:#fff}
input[type=radio]{display:none}
section.tab{display:none;padding:24px 32px 64px;max-width:1400px}
.tab h2{margin:0 0 6px;font-size:18px;font-weight:600}.tab>p{margin:0 0 20px;color:var(--muted);max-width:110ch}
.step{border:1px solid var(--line);border-left:3px solid var(--accent);background:#fff;border-radius:6px;padding:14px 18px;margin-bottom:16px}
.step.fail{border-left-color:var(--fail)}.step h3{margin:0 0 4px;font-size:15px;font-weight:600}
.step .text{margin:0 0 12px;color:var(--muted);font-size:14px;max-width:110ch}
.kv{margin:8px 0}.kv .label{font-size:12px;text-transform:uppercase;letter-spacing:.04em;color:var(--accent);margin-bottom:3px}
.step.fail .kv .label.err{color:var(--fail)}
pre{margin:0;padding:10px 12px;background:#f4f6f8;border:1px solid var(--line);border-radius:4px;font:12.5px/1.45 var(--mono);white-space:pre-wrap;word-break:break-all;max-height:420px;overflow:auto}
footer{padding:16px 32px;color:var(--muted);font-size:12px;border-top:1px solid var(--line)}
</style></head><body>
`

func RenderHTML(w io.Writer, scenarios []*Scenario) {
	fmt.Fprint(w, htmlHead)
	fmt.Fprintf(w, "<header><h1>Seal / Open walkthrough — #1308 prototype</h1><p class=q><strong>Question.</strong> %s</p><p>Static report generated by <code>go run ./research/amqp-seal-prototype -html</code>. Vocabulary per CONTEXT.md “Payload sealing”: Seal, Subject, Two-kid identity, Typed door, Accept-unsealed, Logical kid, Generation, Accept set, Activation, Redelivery, Replay, Duplicate, Dedup key. Card data shown is the published test vector 4111111111111111. Red-edged steps are steps where an opener rule fired (each step's text says whether that was the expected outcome).</p></header>\n", html.EscapeString(Question))

	// Radio inputs must precede the nav/sections they control for the ~ sibling selector.
	for i, s := range scenarios {
		checked := ""
		if i == 0 {
			checked = " checked"
		}
		fmt.Fprintf(w, "<input type=radio name=tab id=%s%s>", s.ID, checked)
	}
	fmt.Fprint(w, "<style>")
	for _, s := range scenarios {
		fmt.Fprintf(w, "#%s:checked~nav label[for=%s]{background:var(--accent);color:#fff;border-color:var(--accent)}#%s:checked~section#tab-%s{display:block}", s.ID, s.ID, s.ID, s.ID)
	}
	fmt.Fprint(w, "</style><nav>")
	for _, s := range scenarios {
		fmt.Fprintf(w, "<label for=%s>%s</label>", s.ID, html.EscapeString(s.Title))
	}
	fmt.Fprint(w, "</nav>\n")

	for _, s := range scenarios {
		fmt.Fprintf(w, "<section class=tab id=tab-%s><h2>%s</h2><p>%s</p>\n", s.ID, html.EscapeString(s.Title), html.EscapeString(s.Description))
		for _, st := range s.Steps {
			cls := "step"
			if st.Failed {
				cls += " fail"
			}
			fmt.Fprintf(w, "<div class=%q><h3>%s</h3>", cls, html.EscapeString(st.Title))
			if st.Text != "" {
				fmt.Fprintf(w, "<p class=text>%s</p>", html.EscapeString(st.Text))
			}
			for _, kv := range st.State {
				lcls := "label"
				if strings.Contains(kv.Label, "FAILED") || strings.HasPrefix(kv.Label, "Startup") || strings.HasPrefix(kv.Label, "Seal failed") {
					lcls += " err"
				}
				fmt.Fprintf(w, "<div class=kv><div class=%q>%s</div><pre>%s</pre></div>", lcls, html.EscapeString(kv.Label), html.EscapeString(kv.Value))
			}
			fmt.Fprint(w, "</div>\n")
		}
		fmt.Fprint(w, "</section>\n")
	}
	fmt.Fprint(w, "<footer>Prototype ≠ implementation: no PayloadError integration, no real keystore module, no messaging client, no ledger table — in-memory stand-ins. Keys are generated per run; jti and the wire bytes differ on every run.</footer></body></html>\n")
}
