custom:
  feature_flag: true
  max_items: 25

  service:
    endpoint: https://api.example.com/v1
    timeout: 3s

  tags: [alpha, beta, gamma]

  meta:
    owner: team-platform
    purpose: demo-custom-params
    region: eu-central-1

