//nolint:dupl // Intentional: Oracle and PostgreSQL stores share structure but differ in SQL dialect
package outbox

import (
	"context"
	"database/sql"
	"fmt"

	dbtypes "github.com/gaborage/go-bricks/database/types"
	"github.com/gaborage/go-bricks/internal/sqlid"
)

// Oracle DDL for the outbox table.
// Uses VARCHAR2 instead of VARCHAR, BLOB instead of BYTEA, CLOB instead of TEXT,
// SYSTIMESTAMP instead of NOW(). The id column has no server-side default —
// the row ID is always generated by the application (uuid.New()) and passed in on Insert.
// Column "error" is renamed to "error_msg" (Oracle reserved word).
const oracleCreateTableSQL = `
CREATE TABLE %s (
    id            VARCHAR2(36) PRIMARY KEY,
    seq           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    lane          VARCHAR2(16) DEFAULT 'amqp' NOT NULL,
    event_type    VARCHAR2(255) NOT NULL,
    aggregate_id  VARCHAR2(255) NOT NULL,
    payload       BLOB NOT NULL,
    headers       BLOB,
    -- Nullable: Oracle treats '' as NULL, so a DEFAULT '' NOT NULL is self-contradictory and
    -- rejects events targeting the AMQP default (empty) exchange with ORA-01400. FetchPending
    -- maps the resulting NULL back to "" on scan. See issue #586.
    exchange      VARCHAR2(255),
    routing_key   VARCHAR2(255),
    stream        VARCHAR2(255),
    partition_key VARCHAR2(255),
    status        VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    retry_count   NUMBER(10) DEFAULT 0 NOT NULL,
    error_msg     CLOB,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    published_at  TIMESTAMP WITH TIME ZONE
)`

// Oracle function-based index for pending events (partial indexes not supported).
const oracleCreatePendingIndexSQL = `
CREATE INDEX idx_%s_pending ON %s (
    CASE WHEN status = 'pending' THEN seq END
)`

// Oracle function-based index for published events cleanup.
const oracleCreatePublishedIndexSQL = `
CREATE INDEX idx_%s_published ON %s (
    CASE WHEN status = 'published' THEN published_at END
)`

// Oracle DDL for the companion leader table and its single row. The relay takes that
// row FOR UPDATE NOWAIT so one instance per ledger drains at a time. MERGE is Oracle's
// idempotent seed: it has no ON CONFLICT.
const oracleCreateLeaderTableSQL = `CREATE TABLE %s (id NUMBER(3) PRIMARY KEY)`

const oracleSeedLeaderRowSQL = `MERGE INTO %s t USING (SELECT 1 AS id FROM dual) s ON (t.id = s.id) WHEN NOT MATCHED THEN INSERT (id) VALUES (s.id)`

// oracleStore is the Oracle outbox store: the shared builder-backed DML with
// the vendor's DDL, the error_msg column (ERROR is reserved) and a NULL-tolerant
// row scanner.
type oracleStore struct {
	sqlStore
}

// NewOracleStore creates a new Oracle outbox store.
// Returns an error if the table name contains invalid identifier characters.
func NewOracleStore(tableName string) (Store, error) {
	if err := validateTableName(tableName); err != nil {
		return nil, err
	}
	return &oracleStore{sqlStore: newSQLStore(dbtypes.Oracle, "oracle", tableName, "error_msg", scanOracleRecord)}, nil
}

// scanOracleRecord reads one FetchPending row. Oracle stores an empty
// exchange/routing_key (the AMQP default exchange) as NULL, because the empty string IS NULL
// in Oracle — so those columns scan NULL-tolerantly and map NULL -> "". See
// issue #586.
func scanOracleRecord(rows *sql.Rows) (Record, error) {
	var r Record
	var exchange, routingKey, stream, partitionKey sql.NullString
	if err := rows.Scan(
		&r.ID, &r.EventType, &r.AggregateID, &r.Payload, &r.Headers,
		&exchange, &routingKey, &r.Lane, &stream, &partitionKey,
		&r.Status, &r.RetryCount, &r.CreatedAt, &r.Seq,
	); err != nil {
		return r, err
	}
	r.Exchange = exchange.String
	r.RoutingKey = routingKey.String
	r.Stream = stream.String
	r.PartitionKey = partitionKey.String
	return r, nil
}

// CreateTable creates the outbox table and indexes in Oracle.
// Unlike PostgreSQL (which uses IF NOT EXISTS), Oracle DDL will return ORA-00955
// if the table or indexes already exist. The caller (ensureStoreInitialized) treats
// all CreateTable errors as warnings, so existing objects are handled gracefully.
// SECURITY: Manual SQL review completed - static DDL constants and the MERGE ... USING dual seed; only the
// constructor-validated table name (validateTableName, ADR-031 grammar) and sqlid's derivations of it are interpolated
func (s *oracleStore) CreateTable(ctx context.Context, db dbtypes.Interface) error {
	idxBase := sqlid.IndexBaseName(s.tableName)

	// Create table (ORA-00955 if already exists — handled by caller as warning)
	if _, err := db.Exec(ctx, fmt.Sprintf(oracleCreateTableSQL, s.tableName)); err != nil {
		return fmt.Errorf("outbox oracle: create table failed: %w", err)
	}

	if _, err := db.Exec(ctx, fmt.Sprintf(oracleCreatePendingIndexSQL, idxBase, s.tableName)); err != nil {
		return fmt.Errorf("outbox oracle: create pending index failed: %w", err)
	}

	if _, err := db.Exec(ctx, fmt.Sprintf(oracleCreatePublishedIndexSQL, idxBase, s.tableName)); err != nil {
		return fmt.Errorf("outbox oracle: create published index failed: %w", err)
	}

	leaderTable := sqlid.LeaderTableName(s.tableName)
	if _, err := db.Exec(ctx, fmt.Sprintf(oracleCreateLeaderTableSQL, leaderTable)); err != nil {
		return fmt.Errorf("outbox oracle: create leader table failed: %w", err)
	}

	if _, err := db.Exec(ctx, fmt.Sprintf(oracleSeedLeaderRowSQL, leaderTable)); err != nil {
		return fmt.Errorf("outbox oracle: seed leader row failed: %w", err)
	}

	return nil
}
