//nolint:dupl // Intentional: PostgreSQL and Oracle stores share structure but differ in SQL dialect
package outbox

import (
	"context"
	"database/sql"
	"fmt"

	dbtypes "github.com/gaborage/go-bricks/database/types"
	"github.com/gaborage/go-bricks/internal/sqlid"
)

// PostgreSQL DDL for the outbox table.
const postgresCreateTableSQL = `
CREATE TABLE IF NOT EXISTS %s (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    seq           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lane          VARCHAR(16) NOT NULL DEFAULT 'amqp',
    event_type    VARCHAR(255) NOT NULL,
    aggregate_id  VARCHAR(255) NOT NULL,
    payload       BYTEA NOT NULL,
    headers       BYTEA,
    exchange      VARCHAR(255) NOT NULL DEFAULT '',
    routing_key   VARCHAR(255) NOT NULL DEFAULT '',
    stream        VARCHAR(255) NOT NULL DEFAULT '',
    partition_key VARCHAR(255) NOT NULL DEFAULT '',
    status        VARCHAR(20) NOT NULL DEFAULT 'pending',
    retry_count   INTEGER NOT NULL DEFAULT 0,
    error         TEXT,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    published_at  TIMESTAMP WITH TIME ZONE
)`

// PostgreSQL index DDL for efficient pending event lookups.
const postgresCreatePendingIndexSQL = `
CREATE INDEX IF NOT EXISTS idx_%s_pending
    ON %s (seq) WHERE status = 'pending'`

// PostgreSQL index DDL for efficient published event cleanup.
const postgresCreatePublishedIndexSQL = `
CREATE INDEX IF NOT EXISTS idx_%s_published
    ON %s (published_at) WHERE status = 'published'`

// PostgreSQL DDL for the companion leader table and its single row. The relay takes
// that row FOR UPDATE NOWAIT so one instance per ledger drains at a time.
const postgresCreateLeaderTableSQL = `CREATE TABLE IF NOT EXISTS %s (id SMALLINT PRIMARY KEY)`

const postgresSeedLeaderRowSQL = `INSERT INTO %s (id) VALUES (1) ON CONFLICT (id) DO NOTHING`

// postgresStore is the PostgreSQL outbox store: the shared builder-backed DML
// with the vendor's DDL and a plain row scanner.
type postgresStore struct {
	sqlStore
}

// NewPostgresStore creates a new PostgreSQL outbox store.
// Returns an error if the table name contains invalid identifier characters.
func NewPostgresStore(tableName string) (Store, error) {
	if err := validateTableName(tableName); err != nil {
		return nil, err
	}
	return &postgresStore{sqlStore: newSQLStore(dbtypes.PostgreSQL, "postgres", tableName, "error", scanPostgresRecord)}, nil
}

// scanPostgresRecord reads one FetchPending row; every column is NOT NULL or
// has a default on PostgreSQL, so the scan is direct.
func scanPostgresRecord(rows *sql.Rows) (Record, error) {
	var r Record
	err := rows.Scan(
		&r.ID, &r.EventType, &r.AggregateID, &r.Payload, &r.Headers,
		&r.Exchange, &r.RoutingKey, &r.Lane, &r.Stream, &r.PartitionKey,
		&r.Status, &r.RetryCount, &r.CreatedAt, &r.Seq,
	)
	return r, err
}

// CreateTable runs the DDL, which stays hand-written: the builder has no DDL
// door and the statements interpolate no value.
//
// SECURITY: Manual SQL review completed - static DDL constants; only the constructor-validated
// table name (validateTableName, ADR-031 grammar) and sqlid's derivations of it are interpolated; no caller value
func (s *postgresStore) CreateTable(ctx context.Context, db dbtypes.Interface) error {
	idxBase := sqlid.IndexBaseName(s.tableName)

	if _, err := db.Exec(ctx, fmt.Sprintf(postgresCreateTableSQL, s.tableName)); err != nil {
		return fmt.Errorf("outbox postgres: create table failed: %w", err)
	}

	if _, err := db.Exec(ctx, fmt.Sprintf(postgresCreatePendingIndexSQL, idxBase, s.tableName)); err != nil {
		return fmt.Errorf("outbox postgres: create pending index failed: %w", err)
	}

	if _, err := db.Exec(ctx, fmt.Sprintf(postgresCreatePublishedIndexSQL, idxBase, s.tableName)); err != nil {
		return fmt.Errorf("outbox postgres: create published index failed: %w", err)
	}

	leaderTable := sqlid.LeaderTableName(s.tableName)
	if _, err := db.Exec(ctx, fmt.Sprintf(postgresCreateLeaderTableSQL, leaderTable)); err != nil {
		return fmt.Errorf("outbox postgres: create leader table failed: %w", err)
	}

	if _, err := db.Exec(ctx, fmt.Sprintf(postgresSeedLeaderRowSQL, leaderTable)); err != nil {
		return fmt.Errorf("outbox postgres: seed leader row failed: %w", err)
	}

	return nil
}
